apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: delete
  storageClassName: basic
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /vol
    server: 172.18.0.9