kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: basic


  #### tridentctl import volume BackendForNasCvoDR trident_pvc_707f6da4_35f5_40b9_a7a6_480dc3be662d_clone -f pvc-import.yaml -n trident