apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi-san
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
allowVolumeExpansion: True
reclaimPolicy: Delete