apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-san-gold
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "ontap-aff-san-backend:aggr1"
allowVolumeExpansion: True
reclaimPolicy: Delete
