kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
  annotations:
    volume.beta.kubernetes.io/storage-class: basic
    trident.netapp.io/exportPolicy: "test"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi